//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SigaApi.Properties
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        public int Id { get; set; }
        public string FacturaId { get; set; }
        public Nullable<System.DateTime> FacturaFecha { get; set; }
        public Nullable<System.DateTime> FacturaVencimiento { get; set; }
        public string MetodoDePago { get; set; }
        public Nullable<decimal> MontoFactura { get; set; }
        public string PedidoId { get; set; }
        public Nullable<int> totalPagado { get; set; }
        public string Sincronizado { get; set; }
    }
}
