//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SigaApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public int ID { get; set; }
        public string activo { get; set; }
        public string codigo { get; set; }
        public string codigoVendedor { get; set; }
        public string direccion { get; set; }
        public string comentario { get; set; }
        public string nombre { get; set; }
        public string telefono1 { get; set; }
        public string telefono2 { get; set; }
        public string compagnia { get; set; }
        public string sincronizado { get; set; }
        public System.DateTime FechaCreacion { get; set; }
    }
}
