//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SigaApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustInvoiceJour
    {
        public string CUSTGROUP { get; set; }
        public int REFNUM { get; set; }
        public string SALESID { get; set; }
        public string ORDERACCOUNT { get; set; }
        public string INVOICEACCOUNT { get; set; }
        public System.DateTime INVOICEDATE { get; set; }
        public System.DateTime DUEDATE { get; set; }
        public decimal CASHDISC { get; set; }
        public System.DateTime CASHDISCDATE { get; set; }
        public decimal QTY { get; set; }
        public decimal VOLUME { get; set; }
        public decimal WEIGHT { get; set; }
        public decimal SUMLINEDISC { get; set; }
        public decimal SALESBALANCE { get; set; }
        public decimal ENDDISC { get; set; }
        public decimal INVOICEAMOUNT { get; set; }
        public string CURRENCYCODE { get; set; }
        public decimal EXCHRATE { get; set; }
        public string INVOICEID { get; set; }
        public string LEDGERVOUCHER { get; set; }
        public int UPDATED { get; set; }
        public decimal ONACCOUNTAMOUNT { get; set; }
        public int TAXPRINTONINVOICE { get; set; }
        public int LISTCODE { get; set; }
        public string DOCUMENTNUM { get; set; }
        public System.DateTime DOCUMENTDATE { get; set; }
        public decimal CASHDISCPERCENT { get; set; }
        public string INTRASTATDISPATCH { get; set; }
        public string DELIVERYNAME { get; set; }
        public string ENTERPRISENUMBER { get; set; }
        public string PURCHASEORDER { get; set; }
        public string DLVTERM { get; set; }
        public string DLVMODE { get; set; }
        public string PAYMENT { get; set; }
        public string CASHDISCCODE { get; set; }
        public decimal INVOICEROUNDOFF { get; set; }
        public decimal SUMMARKUP { get; set; }
        public int COVSTATUS { get; set; }
        public string RETURNITEMNUM { get; set; }
        public string POSTINGPROFILE { get; set; }
        public int BACKORDER { get; set; }
        public int PREPAYMENT { get; set; }
        public string TAXGROUP { get; set; }
        public string TAXITEMGROUP { get; set; }
        public int TAXSPECIFYBYLINE { get; set; }
        public int EINVOICELINESPECIFIC { get; set; }
        public int ONETIMECUSTOMER { get; set; }
        public string PAYMENTSCHED { get; set; }
        public decimal SUMTAX { get; set; }
        public int SALESTYPE { get; set; }
        public string EINVOICEACCOUNTCODE { get; set; }
        public int INTERCOMPANYPOSTED { get; set; }
        public string PARMID { get; set; }
        public string RETURNREASONCODEID { get; set; }
        public string EUSALESLIST { get; set; }
        public decimal EXCHRATESECONDARY { get; set; }
        public int TRIANGULATION { get; set; }
        public string CUSTOMERREF { get; set; }
        public string VATNUM { get; set; }
        public string NUMBERSEQUENCEGROUP { get; set; }
        public string LANGUAGEID { get; set; }
        public int INCLTAX { get; set; }
        public string LOG { get; set; }
        public string PAYMDAYID { get; set; }
        public string INVOICINGNAME { get; set; }
        public int GIROTYPE { get; set; }
        public string CONTACTPERSONID { get; set; }
        public string SALESORIGINID { get; set; }
        public string BILLOFLADINGID { get; set; }
        public string INVENTLOCATIONID { get; set; }
        public System.DateTime FIXEDDUEDATE { get; set; }
        public decimal INVOICEAMOUNTMST { get; set; }
        public decimal INVOICEROUNDOFFMST { get; set; }
        public decimal SUMMARKUPMST { get; set; }
        public decimal SUMLINEDISCMST { get; set; }
        public decimal ENDDISCMST { get; set; }
        public decimal SALESBALANCEMST { get; set; }
        public decimal SUMTAXMST { get; set; }
        public string PRINTMGMTSITEID { get; set; }
        public int RETURNSTATUS { get; set; }
        public string INTERCOMPANYCOMPANYID { get; set; }
        public string INTERCOMPANYPURCHID { get; set; }
        public int PRINTEDORIGINALS { get; set; }
        public int PROFORMA { get; set; }
        public string RCSALESLIST_UK { get; set; }
        public decimal REVERSECHARGE_UK { get; set; }
        public long DELIVERYPOSTALADDRESS { get; set; }
        public long INVOICEPOSTALADDRESS { get; set; }
        public long SOURCEDOCUMENTHEADER { get; set; }
        public long DEFAULTDIMENSION { get; set; }
        public long BANKLCEXPORTLINE { get; set; }
        public long WORKERSALESTAKER { get; set; }
        public long REVERSEDRECID { get; set; }
        public System.DateTime RECEIPTDATECONFIRMED_ES { get; set; }
        public string PAYMID { get; set; }
        public string TAXINVOICESALESID { get; set; }
        public System.DateTime INTRASTATFULFILLMENTDATE_HU { get; set; }
        public string MCREMAIL { get; set; }
        public decimal MCRPAYMAMOUNT { get; set; }
        public decimal MCRDUEAMOUNT { get; set; }
        public System.DateTime CASHDISCBASEDATE { get; set; }
        public long DIRECTDEBITMANDATE { get; set; }
        public int ISCORRECTION { get; set; }
        public long REASONTABLEREF { get; set; }
        public long SOURCEDOCUMENTLINE { get; set; }
        public long TRANSPORTATIONDOCUMENT { get; set; }
        public System.DateTime MODIFIEDDATETIME { get; set; }
        public System.DateTime CREATEDDATETIME { get; set; }
        public int DEL_CREATEDTIME { get; set; }
        public string CREATEDBY { get; set; }
        public string DATAAREAID { get; set; }
        public int RECVERSION { get; set; }
        public long PARTITION { get; set; }
        public long RECID { get; set; }
        public string NCF { get; set; }
        public string TIPO { get; set; }
        public string RNC_CEDULA { get; set; }
        public string CLIENTEDIRECCION { get; set; }
        public string VENDEDORNOMBRE { get; set; }
        public string VENDEDORTELEFONO { get; set; }
        public string TELEFONO { get; set; }
        public string CALLE { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string COUNTRY { get; set; }
        public string NCF_ANTERIOR { get; set; }
        public string NO_FACTURA_ANTERIOR { get; set; }
    }
}
