//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SigaApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTTABLE
    {
        public double CUSTNMBR { get; set; }
        public string CUSTNAME { get; set; }
        public string CUSTCLAS { get; set; }
        public string CPRCSTNM { get; set; }
        public string CNTCPRSN { get; set; }
        public string STMTNAME { get; set; }
        public string SHRTNAME { get; set; }
        public string ADRSCODE { get; set; }
        public string UPSZONE { get; set; }
        public string SHIPMTHD { get; set; }
        public string TAXSCHID { get; set; }
        public string ADDRESS1 { get; set; }
        public string ADDRESS2 { get; set; }
        public string ADDRESS3 { get; set; }
        public string COUNTRY { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string ZIP { get; set; }
        public Nullable<double> PHONE1 { get; set; }
        public Nullable<double> PHONE2 { get; set; }
        public string PHONE3 { get; set; }
        public string FAX { get; set; }
        public string PRBTADCD { get; set; }
        public string PRSTADCD { get; set; }
        public string STADDRCD { get; set; }
        public Nullable<double> SLPRSNID { get; set; }
        public string CHEKBKID { get; set; }
        public string PYMTRMID { get; set; }
        public Nullable<double> CRLMTTYP { get; set; }
        public Nullable<double> CRLMTAMT { get; set; }
        public Nullable<double> CRLMTPER { get; set; }
        public Nullable<double> CRLMTPAM { get; set; }
        public string CURNCYID { get; set; }
        public string RATETPID { get; set; }
        public Nullable<double> CUSTDISC { get; set; }
        public string PRCLEVEL { get; set; }
        public Nullable<double> MINPYTYP { get; set; }
        public Nullable<double> MINPYDLR { get; set; }
        public Nullable<double> MINPYPCT { get; set; }
        public Nullable<double> FNCHATYP { get; set; }
        public Nullable<double> FNCHPCNT { get; set; }
        public Nullable<double> FINCHDLR { get; set; }
        public Nullable<double> MXWOFTYP { get; set; }
        public Nullable<double> MXWROFAM { get; set; }
        public string COMMENT1 { get; set; }
        public string COMMENT2 { get; set; }
        public string USERDEF1 { get; set; }
        public string USERDEF2 { get; set; }
        public string TAXEXMT1 { get; set; }
        public string TAXEXMT2 { get; set; }
        public string TXRGNNUM { get; set; }
        public Nullable<double> BALNCTYP { get; set; }
        public Nullable<double> STMTCYCL { get; set; }
        public string BANKNAME { get; set; }
        public string BNKBRNCH { get; set; }
        public string SALSTERR { get; set; }
        public Nullable<double> DEFCACTY { get; set; }
        public Nullable<double> RMCSHACC { get; set; }
        public Nullable<double> RMARACC { get; set; }
        public Nullable<double> RMSLSACC { get; set; }
        public Nullable<double> RMIVACC { get; set; }
        public Nullable<double> RMCOSACC { get; set; }
        public Nullable<double> RMTAKACC { get; set; }
        public Nullable<double> RMAVACC { get; set; }
        public Nullable<double> RMFCGACC { get; set; }
        public Nullable<double> RMWRACC { get; set; }
        public Nullable<double> RMSORACC { get; set; }
        public Nullable<System.DateTime> FRSTINDT { get; set; }
        public Nullable<double> INACTIVE { get; set; }
        public Nullable<double> HOLD { get; set; }
        public string CRCARDID { get; set; }
        public string CRCRDNUM { get; set; }
        public Nullable<System.DateTime> CCRDXPDT { get; set; }
        public Nullable<double> KPDSTHST { get; set; }
        public Nullable<double> KPCALHST { get; set; }
        public Nullable<double> KPERHIST { get; set; }
        public Nullable<double> KPTRXHST { get; set; }
        public Nullable<double> NOTEINDX { get; set; }
        public Nullable<System.DateTime> CREATDDT { get; set; }
        public Nullable<System.DateTime> MODIFDT { get; set; }
        public Nullable<double> Revalue_Customer { get; set; }
        public Nullable<double> Post_Results_To { get; set; }
        public string FINCHID { get; set; }
        public string GOVCRPID { get; set; }
        public string GOVINDID { get; set; }
        public Nullable<double> DISGRPER { get; set; }
        public Nullable<double> DUEGRPER { get; set; }
        public string DOCFMTID { get; set; }
        public Nullable<double> Send_Email_Statements { get; set; }
        public Nullable<double> USERLANG { get; set; }
        public string GPSFOINTEGRATIONID { get; set; }
        public Nullable<double> INTEGRATIONSOURCE { get; set; }
        public string INTEGRATIONID { get; set; }
        public Nullable<double> ORDERFULFILLDEFAULT { get; set; }
        public Nullable<double> CUSTPRIORITY { get; set; }
        public string CCode { get; set; }
        public string DECLID { get; set; }
        public Nullable<double> RMOvrpymtWrtoffAcctIdx { get; set; }
        public Nullable<double> SHIPCOMPLETE { get; set; }
        public Nullable<double> CBVAT { get; set; }
        public Nullable<double> INCLUDEINDP { get; set; }
        public Nullable<System.DateTime> DEX_ROW_TS { get; set; }
        public Nullable<double> DEX_ROW_ID { get; set; }
        public string Codigo { get; set; }
    }
}
