//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SigaApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTTRANSOPEN
    {
        public decimal EXCHADJUNREALIZED { get; set; }
        public decimal AMOUNTCUR { get; set; }
        public decimal AMOUNTMST { get; set; }
        public System.DateTime DUEDATE { get; set; }
        public long REFRECID { get; set; }
        public long CASHDISCOUNTLEDGERDIMENSION { get; set; }
        public System.DateTime CASHDISCDATE { get; set; }
        public System.DateTime TRANSDATE { get; set; }
        public decimal POSSIBLECASHDISC { get; set; }
        public string ACCOUNTNUM { get; set; }
        public int USECASHDISC { get; set; }
        public System.DateTime LASTINTERESTDATE { get; set; }
        public System.DateTime BANKDISCNOTICEDEADLINE { get; set; }
        public System.DateTime SETTLEMENTPRIORITYCASHDISCDATE { get; set; }
        public long BANKLCEXPORTLINE { get; set; }
        public decimal REPORTINGCURRENCYAMOUNT { get; set; }
        public decimal EXCHADJUNREALIZEDREPORTING { get; set; }
        public decimal TDSAMOUNT_IN { get; set; }
        public decimal TCSAMOUNT_IN { get; set; }
        public decimal INTERESTAMOUNT_BR { get; set; }
        public decimal FINEAMOUNT_BR { get; set; }
        public string INTERESTCODE_BR { get; set; }
        public string FINECODE_BR { get; set; }
        public decimal INTERESTAMOUNTPAYMCUR_BR { get; set; }
        public decimal FINEAMOUNTPAYMCUR_BR { get; set; }
        public decimal TAXWITHHOLDAMOUNTORIGIN_IN { get; set; }
        public decimal SETTLEDLINEPERCENT_IN { get; set; }
        public decimal SETTLEDTOTALAMOUNT_IN { get; set; }
        public string DATAAREAID { get; set; }
        public int RECVERSION { get; set; }
        public long PARTITION { get; set; }
        public long RECID { get; set; }
    }
}
