//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SigaApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTTRAN
    {
        public string ACCOUNTNUM { get; set; }
        public System.DateTime TRANSDATE { get; set; }
        public string VOUCHER { get; set; }
        public string INVOICE { get; set; }
        public string TXT { get; set; }
        public decimal AMOUNTCUR { get; set; }
        public decimal SETTLEAMOUNTCUR { get; set; }
        public decimal AMOUNTMST { get; set; }
        public decimal SETTLEAMOUNTMST { get; set; }
        public string CURRENCYCODE { get; set; }
        public System.DateTime DUEDATE { get; set; }
        public string LASTSETTLEVOUCHER { get; set; }
        public System.DateTime LASTSETTLEDATE { get; set; }
        public string LASTEXCHADJVOUCHER { get; set; }
        public System.DateTime CLOSED { get; set; }
        public int TRANSTYPE { get; set; }
        public int APPROVED { get; set; }
        public decimal EXCHADJUSTMENT { get; set; }
        public string DOCUMENTNUM { get; set; }
        public System.DateTime DOCUMENTDATE { get; set; }
        public decimal LASTEXCHADJRATE { get; set; }
        public int FIXEDEXCHRATE { get; set; }
        public System.DateTime LASTEXCHADJ { get; set; }
        public int CORRECT { get; set; }
        public string BANKCENTRALBANKPURPOSECODE { get; set; }
        public string BANKCENTRALBANKPURPOSETEXT { get; set; }
        public int SETTLEMENT { get; set; }
        public int INTEREST { get; set; }
        public int COLLECTIONLETTER { get; set; }
        public long DEFAULTDIMENSION { get; set; }
        public string POSTINGPROFILECLOSE { get; set; }
        public decimal EXCHRATESECOND { get; set; }
        public long BANKLCEXPORTLINE { get; set; }
        public long ACCOUNTINGEVENT { get; set; }
        public decimal EXCHRATE { get; set; }
        public string LASTSETTLEACCOUNTNUM { get; set; }
        public string COMPANYBANKACCOUNTID { get; set; }
        public string THIRDPARTYBANKACCOUNTID { get; set; }
        public string PAYMMODE { get; set; }
        public string PAYMREFERENCE { get; set; }
        public int PAYMMETHOD { get; set; }
        public int CASHPAYMENT { get; set; }
        public string CONTROLNUM { get; set; }
        public string DELIVERYMODE { get; set; }
        public string POSTINGPROFILE { get; set; }
        public long OFFSETRECID { get; set; }
        public int EUROTRIANGULATION { get; set; }
        public string ORDERACCOUNT { get; set; }
        public string CASHDISCCODE { get; set; }
        public int PREPAYMENT { get; set; }
        public string PAYMSPEC { get; set; }
        public decimal CUSTEXCHADJUSTMENTREALIZED { get; set; }
        public decimal CUSTEXCHADJUSTMENTUNREALIZED { get; set; }
        public System.DateTime PAYMMANLACKDATE { get; set; }
        public string PAYMMANBATCH { get; set; }
        public string PAYMID { get; set; }
        public string BILLOFEXCHANGEID { get; set; }
        public int BILLOFEXCHANGESTATUS { get; set; }
        public int BILLOFEXCHANGESEQNUM { get; set; }
        public string BANKREMITTANCEFILEID { get; set; }
        public int COLLECTIONLETTERCODE { get; set; }
        public int INVOICEPROJECT { get; set; }
        public string LASTSETTLECOMPANY { get; set; }
        public int CANCELLEDPAYMENT { get; set; }
        public long REASONREFRECID { get; set; }
        public decimal REPORTINGCURRENCYAMOUNT { get; set; }
        public decimal REPORTINGEXCHADJUSTMENTREALIZED { get; set; }
        public decimal REPORTINGEXCHADJUSTMENTUNREALIZED { get; set; }
        public decimal LASTEXCHADJRATEREPORTING { get; set; }
        public decimal REPORTINGCURRENCYCROSSRATE { get; set; }
        public decimal EXCHADJUSTMENTREPORTING { get; set; }
        public decimal SETTLEAMOUNTREPORTING { get; set; }
        public long APPROVER { get; set; }
        public string TAXINVOICESALESID { get; set; }
        public string CONCESSIONCONTRACTID { get; set; }
        public string CONCESSIONSETTLEMENTID { get; set; }
        public int RETAILCUSTTRANS { get; set; }
        public string RETAILSTOREID { get; set; }
        public string RETAILTERMINALID { get; set; }
        public string RETAILTRANSACTIONID { get; set; }
        public long CUSTBILLINGCLASSIFICATION { get; set; }
        public string MCRPAYMORDERID { get; set; }
        public long DIRECTDEBITMANDATE { get; set; }
        public System.DateTime MODIFIEDDATETIME { get; set; }
        public int DEL_MODIFIEDTIME { get; set; }
        public string MODIFIEDBY { get; set; }
        public long MODIFIEDTRANSACTIONID { get; set; }
        public System.DateTime CREATEDDATETIME { get; set; }
        public int DEL_CREATEDTIME { get; set; }
        public string CREATEDBY { get; set; }
        public long CREATEDTRANSACTIONID { get; set; }
        public string DATAAREAID { get; set; }
        public int RECVERSION { get; set; }
        public long PARTITION { get; set; }
        public long RECID { get; set; }
        public string NCF { get; set; }
        public string NFC_ANTERIOR { get; set; }
        public string NO_FACTURA_ANTERIOR { get; set; }
    }
}
