//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SigaApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTINVOICETRAN
    {
        public string INVOICEID { get; set; }
        public System.DateTime INVOICEDATE { get; set; }
        public decimal LINENUM { get; set; }
        public string INVENTTRANSID { get; set; }
        public string INVENTREFID { get; set; }
        public string ITEMID { get; set; }
        public string EXTERNALITEMID { get; set; }
        public string NAME { get; set; }
        public string TAXGROUP { get; set; }
        public string CURRENCYCODE { get; set; }
        public decimal PRICEUNIT { get; set; }
        public decimal QTY { get; set; }
        public decimal SALESPRICE { get; set; }
        public decimal DISCPERCENT { get; set; }
        public decimal DISCAMOUNT { get; set; }
        public decimal LINEAMOUNT { get; set; }
        public string SALESGROUP { get; set; }
        public decimal QTYPHYSICAL { get; set; }
        public int PARTDELIVERY { get; set; }
        public decimal REMAIN { get; set; }
        public string SALESID { get; set; }
        public string SALESUNIT { get; set; }
        public decimal SALESMARKUP { get; set; }
        public int COMMISSCALC { get; set; }
        public decimal COMMISSAMOUNTCUR { get; set; }
        public string TRANSACTIONCODE { get; set; }
        public int DELIVERYTYPE { get; set; }
        public string COUNTRYREGIONOFSHIPMENT { get; set; }
        public string ITEMCODEID { get; set; }
        public int TAXAUTOGENERATED { get; set; }
        public string TAXITEMGROUP { get; set; }
        public decimal TAXAMOUNT { get; set; }
        public string TAXWRITECODE { get; set; }
        public decimal MULTILNDISC { get; set; }
        public decimal MULTILNPERCENT { get; set; }
        public decimal LINEDISC { get; set; }
        public decimal LINEPERCENT { get; set; }
        public string ORIGSALESID { get; set; }
        public string LINEHEADER { get; set; }
        public string TRANSPORT { get; set; }
        public string INVENTDIMID { get; set; }
        public string ORIGCOUNTRYREGIONID { get; set; }
        public string NUMBERSEQUENCEGROUP { get; set; }
        public string STATPROCID { get; set; }
        public System.DateTime DLVDATE { get; set; }
        public decimal LINEAMOUNTTAX { get; set; }
        public string PORT { get; set; }
        public string ASSETID { get; set; }
        public int CUSTOMERLINENUM { get; set; }
        public string ASSETBOOKID { get; set; }
        public decimal LINEAMOUNTMST { get; set; }
        public decimal TAXAMOUNTMST { get; set; }
        public decimal LINEAMOUNTTAXMST { get; set; }
        public decimal COMMISSAMOUNTMST { get; set; }
        public decimal SUMLINEDISC { get; set; }
        public decimal SUMLINEDISCMST { get; set; }
        public string INTERCOMPANYINVENTTRANSID { get; set; }
        public decimal OLAPCOSTVALUE { get; set; }
        public string EINVOICEACCOUNTCODE { get; set; }
        public string RETURNDISPOSITIONCODEID { get; set; }
        public decimal STATLINEAMOUNTMST { get; set; }
        public string INTRASTATDISPATCHID { get; set; }
        public decimal INVENTQTY { get; set; }
        public string ORIGSTATE { get; set; }
        public int INVENTREFTYPE { get; set; }
        public string INVENTREFTRANSID { get; set; }
        public decimal WEIGHT { get; set; }
        public System.DateTime RETURNARRIVALDATE { get; set; }
        public System.DateTime RETURNCLOSEDDATE { get; set; }
        public int REVERSECHARGEAPPLIES_UK { get; set; }
        public long REASONREFRECID { get; set; }
        public decimal REMAINBEFORE { get; set; }
        public long SALESCATEGORY { get; set; }
        public long CUSTINVOICELINEIDREF { get; set; }
        public long SOURCEDOCUMENTLINE { get; set; }
        public long DELIVERYPOSTALADDRESS { get; set; }
        public long LEDGERDIMENSION { get; set; }
        public long DEFAULTDIMENSION { get; set; }
        public long TAXWITHHOLDITEMGROUPHEADING_TH { get; set; }
        public int STOCKEDPRODUCT { get; set; }
        public long REVERSEDRECID { get; set; }
        public long NGPCODESTABLE_FR { get; set; }
        public long PARENTRECID { get; set; }
        public string TAXWITHHOLDGROUP_TH { get; set; }
        public System.DateTime INTRASTATFULFILLMENTDATE_HU { get; set; }
        public string BILLINGCODE { get; set; }
        public string MCRDELIVERYNAME { get; set; }
        public string MCRDLVMODE { get; set; }
        public decimal PDSCWQTY { get; set; }
        public decimal PDSCWQTYPHYSICAL { get; set; }
        public decimal PDSCWREMAIN { get; set; }
        public long RETAILCATEGORY { get; set; }
        public System.DateTime MODIFIEDDATETIME { get; set; }
        public System.DateTime CREATEDDATETIME { get; set; }
        public int DEL_CREATEDTIME { get; set; }
        public string CREATEDBY { get; set; }
        public string DATAAREAID { get; set; }
        public int RECVERSION { get; set; }
        public long PARTITION { get; set; }
        public long RECID { get; set; }
    }
}
