//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SigaApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class ECORESPRODUCT
    {
        public Nullable<long> PRODUCTMASTER { get; set; }
        public Nullable<int> RETAITOTALWEIGHT { get; set; }
        public Nullable<int> VARIANTCONFIGURATIONTECHNOLOGY { get; set; }
        public string RETAILCOLORGROUPID { get; set; }
        public string RETAILSIZEGROUPID { get; set; }
        public string RETAILSTYLEGROUPID { get; set; }
        public long INSTANCERELATIONTYPE { get; set; }
        public string DISPLAYPRODUCTNUMBER { get; set; }
        public string SEARCHNAME { get; set; }
        public int PRODUCTTYPE { get; set; }
        public int PDSCWPRODUCT { get; set; }
        public string MODIFIEDBY { get; set; }
        public int RECVERSION { get; set; }
        public long RELATIONTYPE { get; set; }
        public long PARTITION { get; set; }
        public long RECID { get; set; }
    }
}
