//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SigaApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacturaDetalle
    {
        public long ID { get; set; }
        public decimal LineaNumero { get; set; }
        public string ProductoCodigo { get; set; }
        public string Nombre { get; set; }
        public decimal Qty { get; set; }
        public decimal PrecioVenta { get; set; }
        public decimal montoLinea { get; set; }
        public string FacturaId { get; set; }
        public int Sincronizado { get; set; }
        public int IsDelete { get; set; }
        public int Compagnia { get; set; }
    }
}
