//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SigaApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        public int id { get; set; }
        public int Compagnia { get; set; }
        public System.DateTime FacturaFecha { get; set; }
        public string FacturaId { get; set; }
        public System.DateTime FacturaVencimiento { get; set; }
        public int IsDelete { get; set; }
        public string MetodoDePago { get; set; }
        public decimal MontoFactura { get; set; }
        public string PedidoId { get; set; }
        public int sincronizad { get; set; }
        public decimal MontoPendiente { get; set; }
        public string clienteId { get; set; }
        public string clienteNombre { get; set; }
        public int totalPagado { get; set; }
        public string vendedorId { get; set; }
        public Nullable<int> Sincronizado { get; set; }
    }
}
