//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SigaApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacturaDetalle
    {
        public int ID { get; set; }
        public int Compagnia { get; set; }
        public string FacturaId { get; set; }
        public int isDelete { get; set; }
        public decimal LineaNumero { get; set; }
        public string ProductoCodigo { get; set; }
        public string Nombre { get; set; }
        public short Qty { get; set; }
        public decimal PrecioVenta { get; set; }
        public decimal MontoLinea { get; set; }
        public int Sincronizado { get; set; }
    }
}
