//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SigaApi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GRUPOSIGAXEntities : DbContext
    {
        public GRUPOSIGAXEntities()
            : base("name=GRUPOSIGAXEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CustInvoiceJour> CustInvoiceJours { get; set; }
        public DbSet<CUSTINVOICETRAN> CUSTINVOICETRANS { get; set; }
        public DbSet<CUSTTRAN> CUSTTRANS { get; set; }
        public DbSet<CUSTTRANSOPEN> CUSTTRANSOPENs { get; set; }
        public DbSet<ECORESPRODUCT> ECORESPRODUCTs { get; set; }
        public DbSet<ECORESPRODUCTTRANSLATION> ECORESPRODUCTTRANSLATIONs { get; set; }
        public DbSet<INVENTMODELGROUPITEM> INVENTMODELGROUPITEMs { get; set; }
        public DbSet<INVENTTABLEMODULE> INVENTTABLEMODULEs { get; set; }
        public DbSet<CUSTTABLE> CUSTTABLEs { get; set; }
    }
}
