//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SigaApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVENTTABLEMODULE
    {
        public string ITEMID { get; set; }
        public int MODULETYPE { get; set; }
        public string UNITID { get; set; }
        public decimal PRICE { get; set; }
        public decimal PRICEUNIT { get; set; }
        public decimal MARKUP { get; set; }
        public string LINEDISC { get; set; }
        public string MULTILINEDISC { get; set; }
        public int ENDDISC { get; set; }
        public string TAXITEMGROUPID { get; set; }
        public string MARKUPGROUPID { get; set; }
        public System.DateTime PRICEDATE { get; set; }
        public decimal PRICEQTY { get; set; }
        public int ALLOCATEMARKUP { get; set; }
        public decimal OVERDELIVERYPCT { get; set; }
        public decimal UNDERDELIVERYPCT { get; set; }
        public string SUPPITEMGROUPID { get; set; }
        public int INTERCOMPANYBLOCKED { get; set; }
        public long TAXWITHHOLDITEMGROUPHEADING_TH { get; set; }
        public int TAXWITHHOLDCALCULATE_TH { get; set; }
        public decimal MAXIMUMRETAILPRICE_IN { get; set; }
        public decimal PRICESECCUR_RU { get; set; }
        public decimal MARKUPSECCUR_RU { get; set; }
        public int PDSPRICINGPRECISION { get; set; }
        public System.DateTime MODIFIEDDATETIME { get; set; }
        public int DEL_MODIFIEDTIME { get; set; }
        public string MODIFIEDBY { get; set; }
        public System.DateTime CREATEDDATETIME { get; set; }
        public int DEL_CREATEDTIME { get; set; }
        public string CREATEDBY { get; set; }
        public string DATAAREAID { get; set; }
        public int RECVERSION { get; set; }
        public long PARTITION { get; set; }
        public long RECID { get; set; }
    }
}
