//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SigaApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public Invoice()
        {
            this.InvoiceLines = new HashSet<InvoiceLine>();
        }
    
        public int ID { get; set; }
        public string GPID { get; set; }
        public System.DateTime Date { get; set; }
        public int CustomerID { get; set; }
        public decimal Totals { get; set; }
        public decimal VAT { get; set; }
        public decimal Cash { get; set; }
        public decimal Change { get; set; }
        public int Status { get; set; }
        public Nullable<int> IDSaled { get; set; }
        public bool IsNew { get; set; }
        public bool IsInAx { get; set; }
        public Nullable<System.DateTime> IntegrationDate { get; set; }
        public string VendorCode { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ICollection<InvoiceLine> InvoiceLines { get; set; }
    }
}
