//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SigaApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceLine
    {
        public int ID { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<int> ProductID { get; set; }
        public string ProductCode { get; set; }
        public decimal Price { get; set; }
        public Nullable<int> InvoiceID { get; set; }
        public bool IsNew { get; set; }
        public bool IsInAx { get; set; }
        public Nullable<System.DateTime> IntegrationDate { get; set; }
    
        public virtual Invoice Invoice { get; set; }
    }
}
