//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SigaApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoices
    {
        public Invoices()
        {
            this.InvoiceLines = new HashSet<InvoiceLines>();
        }
    
        public int ID { get; set; }
        public string GPID { get; set; }
        public System.DateTime Date { get; set; }
        public int CustomerID { get; set; }
        public decimal Totals { get; set; }
        public decimal VAT { get; set; }
        public decimal Cash { get; set; }
        public decimal Change { get; set; }
        public int Status { get; set; }
        public Nullable<int> IDSaled { get; set; }
        public bool IsNew { get; set; }
        public bool IsInAx { get; set; }
        public Nullable<System.DateTime> IntegrationDate { get; set; }
        public string VendorCode { get; set; }
        public string ifFire { get; set; }
        public Nullable<int> Updatefire { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual ICollection<InvoiceLines> InvoiceLines { get; set; }
    }
}
