//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SigaApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentOrder
    {
        public PaymentOrder()
        {
            this.PaymentItems = new HashSet<PaymentItem>();
        }
    
        public int Id { get; set; }
        public string VendorID { get; set; }
        public System.DateTime Datetime { get; set; }
        public decimal Amount { get; set; }
        public string Method { get; set; }
        public string BankName { get; set; }
        public string CheckNumber { get; set; }
        public Nullable<System.DateTime> CheckDate { get; set; }
        public bool IsEnabled { get; set; }
        public string Customer_Code { get; set; }
        public bool IsOpen { get; set; }
        public bool Imported { get; set; }
    
        public virtual ICollection<PaymentItem> PaymentItems { get; set; }
    }
}
