//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SigaApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentOrder
    {
        public PaymentOrder()
        {
            this.PaymentItems = new HashSet<PaymentItem>();
        }
    
        public int Id { get; set; }
        public string VendorID { get; set; }
        public System.DateTime Datetime { get; set; }
        public decimal Amount { get; set; }
        public string Method { get; set; }
        public string BankName { get; set; }
        public string CheckNumber { get; set; }
        public Nullable<System.DateTime> CheckDate { get; set; }
        public bool IsEnabled { get; set; }
        public string Customer_Code { get; set; }
        public bool IsOpen { get; set; }
        public bool Imported { get; set; }
    
        public virtual ICollection<PaymentItem> PaymentItems { get; set; }
    }
}
