//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SigaApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentItem
    {
        public int Id { get; set; }
        public int PaymentOrderId { get; set; }
        public string InvoiceNumber { get; set; }
        public decimal AmountApply { get; set; }
        public decimal InvoiveAmountAtMoment { get; set; }
        public bool IsEnabled { get; set; }
    
        public virtual PaymentOrder PaymentOrder { get; set; }
    }
}
