//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SigaApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentItem
    {
        public int Id { get; set; }
        public int PaymentOrderId { get; set; }
        public string InvoiceNumber { get; set; }
        public decimal AmountApply { get; set; }
        public decimal InvoiveAmountAtMoment { get; set; }
        public bool IsEnabled { get; set; }
    
        public virtual PaymentOrder PaymentOrder { get; set; }
    }
}
