//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SigaApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class producto
    {
        public int Cantidad { get; set; }
        public string Codigo { get; set; }
        public int Compagnia { get; set; }
        public long Id { get; set; }
        public int IsDelete { get; set; }
        public string Nombre { get; set; }
        public string OuM { get; set; }
        public decimal Precio { get; set; }
        public int Sincronizado { get; set; }
        public int actualizar { get; set; }
        public string TipodeVenta { get; set; }
    }
}
