//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SigaApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesOrder
    {
        public SalesOrder()
        {
            this.SalesLines = new HashSet<SalesLine>();
        }
    
        public int ID { get; set; }
        public decimal Cash { get; set; }
        public decimal Change { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime Date { get; set; }
        public string GPID { get; set; }
        public bool IsDelete { get; set; }
        public decimal Totals { get; set; }
        public decimal VAT { get; set; }
        public string UserName { get; set; }
        public string UserCode { get; set; }
        public Nullable<int> UserID { get; set; }
        public int Status { get; set; }
        public string Commets { get; set; }
        public Nullable<int> CustomerID { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ICollection<SalesLine> SalesLines { get; set; }
    }
}
