//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SigaApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesLine
    {
        public int ID { get; set; }
        public decimal Price { get; set; }
        public int Qty { get; set; }
        public int ProductID { get; set; }
        public string ProductCode { get; set; }
        public Nullable<int> Products_ID { get; set; }
        public Nullable<int> SalesOrdersID { get; set; }
        public string ProductName { get; set; }
    
        public virtual SalesOrder SalesOrder { get; set; }
    }
}
